%computeBottomScattering - compute the bottom scattering strength
%
% ScatteringStrength = ...
%   computeBottomScattering(Environment, ...
%                           Frequency, ...
%                           InAngle, ...
%                           OutAngle, ...
%                           OffAxisAngle, ...
%                           {PropertyList})
%
% computes the bistatic scattering strength, in dB, of the
% bottom. The bottom parameters are taken from the environment
% structure.
%
% 
